#!/usr/bin/env python3
"""Generates worlds/turtlebot3_maze.world for the MTRX3760 Project 1 simulation.

The maze is described as a grid of square cells plus a list of the openings
between neighbouring cells. Every cell boundary that is not listed as an
opening becomes a wall. Runs of wall along the same grid line are merged into
one box so the world file stays short and the walls have no seams.

Usage:
    python3 make_maze_world.py > ../turtlebot3_gazebo/worlds/turtlebot3_maze.world

The same wall list can be written as plain text (one "cx cy sx sy" box per
line) with --walls, which is what the offline test harness reads.
"""

import sys

# ---Maze geometry [m]---------------------------------------------------------
CELL_SIZE = 1.0          # centre-to-centre spacing of the grid lines
WALL_THICKNESS = 0.06
WALL_HEIGHT = 0.30       # taller than the lidar (0.17 m) and the camera
COLUMNS = 5              # cells along x, lettered A to E
ROWS = 4                 # cells along y, numbered 0 to 3

# ---Openings between neighbouring cells, as ((column, row), (column, row))----
# The openings form a tree: every cell is reachable and there are no loops, so
# there are no floating rooms and a wall follower is guaranteed to get out.
OPENINGS = [
    ((0, 0), (1, 0)), ((1, 0), (2, 0)), ((2, 0), (3, 0)), ((3, 0), (4, 0)),
    ((4, 0), (4, 1)), ((4, 1), (3, 1)), ((3, 1), (3, 2)), ((3, 2), (4, 2)),
    ((3, 2), (3, 3)), ((3, 3), (4, 3)), ((3, 1), (2, 1)), ((2, 1), (2, 2)),
    ((2, 2), (2, 3)), ((2, 2), (1, 2)), ((1, 0), (1, 1)), ((1, 1), (0, 1)),
    ((0, 1), (0, 2)), ((0, 2), (0, 3)), ((0, 3), (1, 3)),
]

# The way out: a gap in the outer wall on the east side of this cell.
EXIT_CELL = (4, 3)


def is_open(cell_a, cell_b):
    """True when there is an opening between two neighbouring cells."""
    return (cell_a, cell_b) in OPENINGS or (cell_b, cell_a) in OPENINGS


def wall_runs():
    """Returns the walls as (x_start, y_start, x_end, y_end) centre lines."""
    runs = []

    # Walls running north-south sit on the vertical grid lines x = column * S.
    for column in range(COLUMNS + 1):
        run_start = None
        for row in range(ROWS + 1):
            walled = False
            if row < ROWS:
                if column == 0:
                    walled = True
                elif column == COLUMNS:
                    walled = (column - 1, row) != EXIT_CELL
                else:
                    walled = not is_open((column - 1, row), (column, row))
            if walled and run_start is None:
                run_start = row
            if not walled and run_start is not None:
                runs.append((column * CELL_SIZE, run_start * CELL_SIZE,
                             column * CELL_SIZE, row * CELL_SIZE))
                run_start = None

    # Walls running east-west sit on the horizontal grid lines y = row * S.
    for row in range(ROWS + 1):
        run_start = None
        for column in range(COLUMNS + 1):
            walled = False
            if column < COLUMNS:
                if row == 0 or row == ROWS:
                    walled = True
                else:
                    walled = not is_open((column, row - 1), (column, row))
            if walled and run_start is None:
                run_start = column
            if not walled and run_start is not None:
                runs.append((run_start * CELL_SIZE, row * CELL_SIZE,
                             column * CELL_SIZE, row * CELL_SIZE))
                run_start = None

    return runs


def wall_boxes():
    """Returns each wall as (centre_x, centre_y, size_x, size_y).

    Each box is lengthened by one wall thickness so that walls meeting at a
    corner overlap and leave no notch.
    """
    boxes = []
    for (x_start, y_start, x_end, y_end) in wall_runs():
        centre_x = 0.5 * (x_start + x_end)
        centre_y = 0.5 * (y_start + y_end)
        size_x = abs(x_end - x_start) + WALL_THICKNESS
        size_y = abs(y_end - y_start) + WALL_THICKNESS
        boxes.append((centre_x, centre_y, size_x, size_y))
    return boxes


WORLD_HEADER = """<?xml version="1.0"?>
<!--
  turtlebot3_maze.world

  Enclosed maze for the MTRX3760 Project 1 right wall follower. {columns} x {rows}
  cells of {cell} m, no floating rooms. The robot starts in the south-west cell
  facing east, with the outer wall on its right, and leaves through the gap in
  the east wall of the north-east cell.

  Generated by tools/make_maze_world.py: change the maze there, not here.
-->
<sdf version="1.8">
  <world name="default">
    <physics type="ode">
      <real_time_update_rate>1000.0</real_time_update_rate>
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1</real_time_factor>
      <ode>
        <solver>
          <type>quick</type>
          <iters>150</iters>
          <precon_iters>0</precon_iters>
          <sor>1.400000</sor>
          <use_dynamic_moi_rescaling>1</use_dynamic_moi_rescaling>
        </solver>
        <constraints>
          <cfm>0.00001</cfm>
          <erp>0.2</erp>
          <contact_max_correcting_vel>2000.000000</contact_max_correcting_vel>
          <contact_surface_layer>0.01000</contact_surface_layer>
        </constraints>
      </ode>
    </physics>
    <plugin
      filename="gz-sim-physics-system"
      name="gz::sim::systems::Physics">
    </plugin>
    <plugin
      filename="gz-sim-user-commands-system"
      name="gz::sim::systems::UserCommands">
    </plugin>
    <plugin
      filename="gz-sim-scene-broadcaster-system"
      name="gz::sim::systems::SceneBroadcaster">
    </plugin>
    <plugin
      filename="gz-sim-sensors-system"
      name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin
      filename="gz-sim-imu-system"
      name="gz::sim::systems::Imu">
    </plugin>

    <scene>
      <shadows>false</shadows>
    </scene>

    <gui fullscreen='0'>
      <camera name='user_camera'>
        <pose frame=''>{view_x:.2f} {view_y:.2f} 7.5 0 1.5138 0</pose>
        <view_controller>orbit</view_controller>
        <projection_type>perspective</projection_type>
      </camera>
    </gui>

    <light type="directional" name="sun">
      <cast_shadows>false</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.8 0.8 0.8 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <attenuation>
        <range>1000</range>
        <constant>0.9</constant>
        <linear>0.01</linear>
        <quadratic>0.001</quadratic>
      </attenuation>
      <direction>-0.5 0.1 -0.9</direction>
    </light>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>100 100</size>
            </plane>
          </geometry>
          <surface>
            <friction>
              <ode>
                <mu>100</mu>
                <mu2>50</mu2>
              </ode>
            </friction>
          </surface>
        </collision>
        <visual name="visual">
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>100 100</size>
            </plane>
          </geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
      </link>
    </model>

    <model name="maze">
      <static>true</static>
      <link name="walls">
"""

WALL_TEMPLATE = """        <collision name="wall_{index}_collision">
          <pose>{x:.3f} {y:.3f} {z:.3f} 0 0 0</pose>
          <geometry>
            <box>
              <size>{sx:.3f} {sy:.3f} {sz:.3f}</size>
            </box>
          </geometry>
        </collision>
        <visual name="wall_{index}_visual">
          <pose>{x:.3f} {y:.3f} {z:.3f} 0 0 0</pose>
          <geometry>
            <box>
              <size>{sx:.3f} {sy:.3f} {sz:.3f}</size>
            </box>
          </geometry>
          <material>
            <ambient>{colour} 1</ambient>
            <diffuse>{colour} 1</diffuse>
            <specular>0.1 0.1 0.1 1</specular>
          </material>
        </visual>
"""

WORLD_FOOTER = """      </link>
    </model>
  </world>
</sdf>
"""

# Walls along x and walls along y get different colours so that corners show
# up in the camera image.
COLOUR_ALONG_X = "0.85 0.55 0.25"
COLOUR_ALONG_Y = "0.30 0.50 0.75"


def world_text():
    """Returns the complete SDF world as a string."""
    text = WORLD_HEADER.format(
        columns=COLUMNS, rows=ROWS, cell=CELL_SIZE,
        view_x=0.5 * COLUMNS * CELL_SIZE - 0.43,
        view_y=0.5 * ROWS * CELL_SIZE)
    for index, (x, y, sx, sy) in enumerate(wall_boxes()):
        colour = COLOUR_ALONG_X if sx > sy else COLOUR_ALONG_Y
        text += WALL_TEMPLATE.format(
            index=index, x=x, y=y, z=0.5 * WALL_HEIGHT,
            sx=sx, sy=sy, sz=WALL_HEIGHT, colour=colour)
    text += WORLD_FOOTER
    return text


def main():
    if len(sys.argv) > 1 and sys.argv[1] == "--walls":
        for (x, y, sx, sy) in wall_boxes():
            print("{:.3f} {:.3f} {:.3f} {:.3f}".format(x, y, sx, sy))
    else:
        sys.stdout.write(world_text())


if __name__ == "__main__":
    main()
